name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
          key: ${{ runner.os }}-dependencies

      - name: install GoogleTest
        if: ${{ steps.cache.output.cache-hit != 'true' }}
        run: |
          cd ..
          git clone https://github.com/google/googletest.git --branch release-1.12.1
          cd googletest
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION
          cmake --build build --config Release
          cmake --build build --target install --config Release

      - name: install glfw
        if: ${{ steps.cache.output.cache-hit != 'true' }}
        run: |
          cd ..
          sudo apt update
          sudo apt install libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev libtbb-dev

      - name: configure
        run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION -DProject_ENABLE_CODE_COVERAGE=1

      - name: build
        run: cmake --build build --config $BUILD_TYPE -j4

      - name: run tests
        run: |
          cd build
          ctest -C $BUILD_TYPE -VV
          
      - name: upload
        uses: actions/upload-artifact@v2
        with: 
          name: build
          path: build
